============================================================  
-- ARCADIA - BASE DE DATOS SQL SERVER  
-- ============================================================  

IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = 'Arcadia')  
    CREATE DATABASE Arcadia;  
GO  

USE Arcadia;  
GO  

CREATE TABLE Users(  
    UserId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,  
    UserName NVARCHAR(20) NOT NULL UNIQUE,  
    DisplayName NVARCHAR(50) NOT NULL,  
    Email NVARCHAR(255) NOT NULL UNIQUE,  
    PasswordHash NVARCHAR(30) NOT NULL,  
    AvatarURL NVARCHAR(255) NULL,  
    Bio NVARCHAR(255) NULL,  
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),  
    UpdatedAt DATETIME2 NULL,  
    DeletedAt DATETIME2 NULL  
);  
GO  

CREATE TABLE DirectMessages(  
    MessageId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,  
    SenderUserId UNIQUEIDENTIFIER NOT NULL,  
    ReceiverUserId UNIQUEIDENTIFIER NOT NULL,  
    Content NVARCHAR(1000) NOT NULL,  
    SentAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),  
    IsRead BIT NOT NULL DEFAULT 0,  
    Edited BIT NOT NULL DEFAULT 0,  
    DeletedAt DATETIME2 NULL,  

    CONSTRAINT FK_DirectMessage_Sender FOREIGN KEY (SenderUserId) REFERENCES Users(UserId),  
    CONSTRAINT FK_DirectMessage_Receiver FOREIGN KEY (ReceiverUserId) REFERENCES Users(UserId)  
);  
GO  

CREATE TABLE Notifications(  
    NotificationId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,  
    UserId UNIQUEIDENTIFIER NOT NULL,  
    Type NVARCHAR(50) NOT NULL,  
    Message NVARCHAR(255) NOT NULL,  
    IsRead BIT NOT NULL DEFAULT 0,  
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),  

    CONSTRAINT FK_Notification_User FOREIGN KEY (UserId) REFERENCES Users(UserId)  
);  
GO  

CREATE TABLE Posts(  
    PostId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,  
    UserId UNIQUEIDENTIFIER NOT NULL,  
    Title NVARCHAR(100) NOT NULL,  
    Description NVARCHAR(1000) NULL,  
    ImageURL NVARCHAR(255) NULL,  
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),  
    UpdatedAt DATETIME2 NULL,  
    DeletedAt DATETIME2 NULL,

    CONSTRAINT FK_Post_User FOREIGN KEY (UserId) REFERENCES Users(UserId)  
);  
GO  

CREATE TABLE Comments(  
    CommentId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,  
    UserId UNIQUEIDENTIFIER NOT NULL,  
    PostId UNIQUEIDENTIFIER NOT NULL,  
    Content NVARCHAR(1000) NOT NULL,  
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),  
    UpdatedAt DATETIME2 NULL,  
    DeletedAt DATETIME2 NULL,

    CONSTRAINT FK_Comments_User FOREIGN KEY (UserId) REFERENCES Users(UserId),  
    CONSTRAINT FK_Comments_Post FOREIGN KEY (PostId) REFERENCES Posts(PostId)  
);  
GO  

CREATE TABLE Tags(  
    TagId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,  
    TagName NVARCHAR(50) NOT NULL UNIQUE --?  
);  
GO  

CREATE TABLE PostTags(  
    PostTagId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,  
    PostId UNIQUEIDENTIFIER NOT NULL,  
    TagId UNIQUEIDENTIFIER NOT NULL,  

    CONSTRAINT FK_PostTag_Post FOREIGN KEY (PostId) REFERENCES Posts(PostId),  
    CONSTRAINT FK_PostTag_Tag FOREIGN KEY (TagId) REFERENCES Tags(TagId)  
);  
GO  

CREATE TABLE Clubs(  
    ClubId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,  
    ClubName NVARCHAR(50) NOT NULL UNIQUE,  
    DisplayName NVARCHAR(100) NOT NULL,  
    Description NVARCHAR(255) NULL,  
    IconURL NVARCHAR(255) NULL,  
    IsPrivate BIT NOT NULL DEFAULT 0,  
    CreatorUserId UNIQUEIDENTIFIER NOT NULL,  
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),  
    UpdatedAt DATETIME2 NULL,  
    DeletedAt DATETIME2 NULL,  

    CONSTRAINT FK_Club_User FOREIGN KEY (CreatorUserId) REFERENCES Users(UserId)  
);  
GO  

CREATE TABLE ClubUsers(  
    ClubUserId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,  
    ClubId UNIQUEIDENTIFIER NOT NULL,  
    UserId UNIQUEIDENTIFIER NOT NULL,  
    Status NVARCHAR(50) NOT NULL,  
    JoinedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),  

    CONSTRAINT FK_ClubUsers_Club FOREIGN KEY (ClubId) REFERENCES Clubs(ClubId),  
    CONSTRAINT FK_ClubUsers_User FOREIGN KEY (UserId) REFERENCES Users(UserId)  
);  
GO  

CREATE TABLE ClubPosts(  
    ClubPostId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,  
    ClubId UNIQUEIDENTIFIER NOT NULL,  
    PostId UNIQUEIDENTIFIER NOT NULL,  

    CONSTRAINT FK_ClubPosts_Club FOREIGN KEY (ClubId) REFERENCES Clubs(ClubId),  
    CONSTRAINT FK_ClubPosts_Post FOREIGN KEY (PostId) REFERENCES Posts(PostId)  
);  
GO  

CREATE TABLE Boards(  
    BoardId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,  
    UserId UNIQUEIDENTIFIER NOT NULL,  
    BoardName NVARCHAR(100) NOT NULL,  
    IsPrivate BIT NOT NULL DEFAULT 0,  
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),  
    UpdatedAt DATETIME2 NULL,  
    DeletedAt DATETIME2 NULL,  

    CONSTRAINT FK_Board_User FOREIGN KEY (UserId) REFERENCES Users(UserId)  
);  
GO  

CREATE TABLE BoardPosts(  
    BoardPostId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,  
    BoardId UNIQUEIDENTIFIER NOT NULL,  
    PostId UNIQUEIDENTIFIER NOT NULL,  
    SavedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	
    CONSTRAINT FK_BoardPost_Board FOREIGN KEY (BoardId) REFERENCES Boards(BoardId),  
    CONSTRAINT FK_BoardPost_Post FOREIGN KEY (PostId) REFERENCES Posts(PostId)  
);  
GO  

-- Nueva tabla: Reacciones predeterminadas  
CREATE TABLE ReactionType (  
    ReactionTypeId INT PRIMARY KEY,  
    Name NVARCHAR(20) UNIQUE  
);  
GO  

-- Cambio en el manejo de las reacciones (más general)  
CREATE TABLE PostReactions (  
    PostReactionId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),  
    UserId UNIQUEIDENTIFIER NOT NULL,  
    PostId UNIQUEIDENTIFIER NOT NULL,  
    ReactionTypeId INT NOT NULL,  
    CreatedAt DATETIME2 DEFAULT SYSUTCDATETIME(),  

    CONSTRAINT FK_PostReaction_User FOREIGN KEY (UserId) REFERENCES Users(UserId),  
    CONSTRAINT FK_PostReaction_Post FOREIGN KEY (PostId) REFERENCES Posts(PostId),  
    CONSTRAINT FK_PostReaction_Type FOREIGN KEY (ReactionTypeId) REFERENCES ReactionType(ReactionTypeId)  
);  
GO  